In [ ]:
from sklearn.model_selection import StratifiedKFold
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "X": list(range(100)),
    'Y': [_//10 for _ in range(100)]
})

df['Y'].value_counts()

In [24]:
df

,X,Y
0,0,0
1,1,0
2,2,0
3,3,0
4,4,0
...,...,...
95,95,9
96,96,9
97,97,9
98,98,9


# 第一个特征，shuffle和不shuffle的区别

In [25]:
skf = StratifiedKFold(n_splits=5, shuffle=False)

for fold, (train_idx, val_idx) in enumerate(skf.split(X=df['X'], y=df['Y'])):
    print(val_idx)


[ 0  1 10 11 20 21 30 31 40 41 50 51 60 61 70 71 80 81 90 91]
[ 2  3 12 13 22 23 32 33 42 43 52 53 62 63 72 73 82 83 92 93]
[ 4  5 14 15 24 25 34 35 44 45 54 55 64 65 74 75 84 85 94 95]
[ 6  7 16 17 26 27 36 37 46 47 56 57 66 67 76 77 86 87 96 97]
[ 8  9 18 19 28 29 38 39 48 49 58 59 68 69 78 79 88 89 98 99]


可以看到，每个类别都均匀分了1/5，例如标签0，有0、1，1有10，11
由于这里shuffle=False，所以没有打乱

In [26]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=2666)

for fold, (train_idx, val_idx) in enumerate(skf.split(X=df['X'], y=df['Y'])):
    print(val_idx)

[ 1  6 13 17 23 27 30 33 45 46 52 55 61 62 70 75 80 83 97 98]
[ 4  8 15 16 25 28 32 37 42 43 56 58 65 68 73 78 81 88 90 94]
[ 2  5 12 19 21 24 31 39 47 48 54 57 60 63 71 76 82 89 91 96]
[ 0  3 10 14 20 26 34 35 41 44 50 51 66 67 74 79 84 85 92 99]
[ 7  9 11 18 22 29 36 38 40 49 53 59 64 69 72 77 86 87 93 95]


这里标签0就是1，6，标签1就是4，8，说明在这个label组内顺序被打乱了

# 第二个特性，所有fold val_idx集合到一起会覆盖所有样本

In [27]:
oof = np.full(shape=df.shape[0], fill_value=-100)

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=2666)

for fold, (train_idx, val_idx) in enumerate(skf.split(X=df['X'], y=df['Y'])):
    oof[val_idx] = 1
    
    
assert (oof==1).all()